server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html;

    # Route semua halaman ke file html
    location = /login    { try_files /login.html =404; }
    location = /register { try_files /register.html =404; }
    location = /isisaldo { try_files /isisaldo.html =404; }
    location = /product  { try_files /product.html =404; }
    location = /contact  { try_files /contact.html =404; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
